# Generated by Django 5.1.4 on 2025-01-16 06:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chicago', '0002_alter_venta_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ('-fecha_venta',)},
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='total',
            new_name='precio_total',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='fecha',
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='Imagenes_Perfil')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Chicago.vendedor'),
            preserve_default=False,
        ),
    ]
